name: Documentation

on:
  push:
    branches:
      - main
  pull_request:
    branches-ignore:
      - main

jobs:
  Docs:
    name: Generate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Project
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Use Node.js v20
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: yarn
          registry-url: https://registry.npmjs.org/
      - name: Install Dependencies
        run: yarn --immutable
      - name: Generate Docs
        run: yarn docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@373f7f263a76c20808c831209c920827a82a2847 # v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
